<?= $this->doctype() ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <!-- Latest compiled and minified CSS-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <?= $this->headLink()->prependStylesheet("https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css") ?>
    <?= $this->headLink()->prependStylesheet($this->basePath('/css/combobox.css')) ?>

    <!-- Scripts -->
    <?= $this->headScript()->appendFile("https://code.jquery.com/jquery-1.12.4.js") ?>
    <?= $this->headScript()->appendFile("https://code.jquery.com/ui/1.12.1/jquery-ui.js") ?>
    <?= $this->headScript()->appendFile($this->basePath('js/combobox2.js')) ?>

</head>
<body>
<div class="container">
    <?= $this->content ?>
    <hr>
    <footer>
        <p> footer here.</p>
    </footer>
</div>
<?= $this->inlineScript() ?>
</body>
</html>
