<?php
$title = "Edit author information";
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$form->setAttribute('action', $this->url('biblio', [
        'action' => 'editAuthor',
        'id' => $id,
    ]
));
$form->prepare();
?>

<?php
echo $this->form()->openTag($form); ?>
<div class="form-group">
<?php
echo $this->formRow($form->get('author_id'));
?></div><div class="form-group"><?php
echo $this->formRow($form->get('author_name'));
?></div><?php
echo $this->formElement($form->get('submit'));
echo $this->form()->closeTag();
?>
