<?php
$title = 'Bibliography: References';
$this->headTitle($title);
?>
<h1><?php $this->escapeHtml($title) ?></h1>
<div id="bibliography">
    <table class="table">
        <tr>
            <th>Reference ID</th>
            <th>Bibliography ID </th>
            <th>Bibliography notes </th>
            <th>Reference type </th>
            <th>Reference type option </th>
            <th>&nbsp;</th>
        </tr>
    <?php foreach ($references as $referenceId => $referenceInfo) { ?>
        <tr>
            <td><?php echo $referenceInfo->ref_id ?> </td>
            <td><?php echo $referenceInfo->bibliog_item['abbrev'] ?> </td>
            <td><?php echo $referenceInfo->bibliog_note ?> </td>
            <td><?php echo $referenceInfo->ref_type ?> </td>
            <td><?php echo $referenceInfo->ref_type_id ?> </td>
            <td><a href="<?= $this->url('biblio', ['action' => 'editReference', 'id' => $referenceInfo->ref_id]) ?>">Edit</a>
                / Delete </td>
        </tr>
    <?php } ?>
    </table>
    <a href="<?php echo $this->url('biblio', ['action' => 'addReference']) ?>" class="btn btn-default">Add reference</a>
</div>