<?php
$title = "Add new author ";
$this->headTitle($title);
?>
<h2><?= $this->escapeHtml($title) ?></h2>

<?php
$form->setAttribute('action', $this->url('biblio', [
        'action' => 'addAuthor'
    ]
));
$form->prepare();
?>

<?php
echo $this->form()->openTag($form);
?><div class='form-group'>
<br>
</div><div class='form-group'><?php
    echo $this->formRow($form->get('author_name'));
echo "<br>";
?></div>
<div class="clearfix">&nbsp</div>
<?php
echo $this->formElement($form->get('submit'));
echo $this->form()->closeTag();
?>