<?php
$title = "Edit bibliographic information";
$this->headTitle($title);
?>
<?= $this->headScript()->appendFile($this->basePath('js/Site/leaffunctions.js')) ?>
    <h1><?= $this->escapeHtml($title) ?></h1>
<?php
$form->setAttribute('action', $this->url('biblio', [
        'action' => 'add'
    ]
));
$form->prepare();
?>

<?php
echo $this->form()->openTag($form);
?><div class='form-group'><?php
echo $this->formRow($form->get('bibliog_id'));
echo "<br>";
?></div><div class='form-group'><?php
echo $this->formRow($form->get('edited'));
echo "<br>";
    ?></div><div class='form-group'><?php
echo $this->formRow($form->get('year'));
echo "<br>";
    ?></div><div class='form-group'><?php
echo $this->formRow($form->get('title'));
echo "<br>";
    ?></div><div class='form-group'><?php
echo $this->formRow($form->get('journal'));
echo "<br>";
    ?></div><div class='form-group'><?php
echo $this->formRow($form->get('issue'));
echo "<br>";
    ?></div><div class='form-group'><?php
echo $this->formRow($form->get('series'));
echo "<br>";
    ?></div><div class='form-group'><?php
echo $this->formRow($form->get('series_vol'));
echo "<br>";
    ?></div><div class='form-group'><?php
echo $this->formRow($form->get('publish_info'));
echo "<br>";
    ?></div><div class='form-group'><?php
echo $this->formRow($form->get('pages'));
echo "<br>";
    ?></div><div class='form-group'><?php
echo $this->formCollection($form->get('authors'));
echo "<br>"; ?>
    ?></div>
<button onclick="return add_form_element()">Add another author </button>
<?php
echo $this->formElement($form->get('submit'));
echo $this->form()->closeTag();
?>
