<?php
$title = "Edit author information";
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$form->setAttribute('action', $this->url('biblio', [
        'action' => 'editAuthor',
        'id' => $id,
    ]
));
$form->prepare();
?>

<?php
echo $this->form()->openTag($form);
echo $this->formRow($form->get('author_id'));
echo "<br>";
echo $this->formRow($form->get('author_name'));
echo "<br>";

echo $this->formElement($form->get('submit'));
echo $this->form()->closeTag();
?>
