<?php
$title = "Edit bibliographic information";
$this->headTitle($title);
?>
    <h1><?= $this->escapeHtml($title) ?></h1>
<?php
$form->setAttribute('action', $this->url('biblio', [
        'action' => 'edit',
        'id' => $id,
    ]
));
$form->prepare();
?>

<?php
echo $this->form()->openTag($form);
echo $this->formRow($form->get('bibliog_id'));
echo "<br>";
echo $this->formRow($form->get('edited'));
echo "<br>";
echo $this->formRow($form->get('year'));
echo "<br>";
echo $this->formRow($form->get('title'));
echo "<br>";
echo $this->formRow($form->get('journal'));
echo "<br>";
echo $this->formRow($form->get('issue'));
echo "<br>";
echo $this->formRow($form->get('pages'));
echo "<br>";
echo $this->formCollection($form->get('authors'));
echo "<br>";
?>
<button onclick="return add_form_element()">Add another author </button>
<?php
echo $this->formElement($form->get('submit'));
echo $this->form()->closeTag();
?>
