<?php
$title = "Edit reference information";
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$form->setAttribute('action', $this->url('biblio', [
        'action' => 'editReference',
        'id' => $id,
    ]
));
$form->prepare();
?>

<?php
echo $this->form()->openTag($form);
echo $this->formRow($form->get('ref_id'));
echo "<br>";
echo $this->formRow($form->get('ref_type'));
echo "<br>";
echo $this->formRow($form->get('ref_type_id'));
echo "<br>";
echo $this->formRow($form->get('bibliog_id'));
echo "<br>";
echo $this->formRow($form->get('bibliog_note'));
echo "<br>";

echo $this->formElement($form->get('submit'));
echo $this->form()->closeTag();
?>
